### ISSUE TITLE
I cannot log in

### ISSUE THREAD

**Issue by donghoon-shin** [YukiGasai/obsidian-google-calendar#62] opened 2023-02-04 02:10 UTC
If I try to log in, I see below message.

### This app tried to access sensitive info in your Google Account. To keep your account safe, Google blocked this access.

What can I do...?

**Comment by YukiGasai** [comment] 2023-02-04 10:40
The test Client is full please use your own client

**Comment by YukiGasai** [comment] 2023-02-09 16:31
Duplicate of #49

**Closed by YukiGasai** 2023-02-09 16:31 UTC
