### ISSUE TITLE
Unable to login on Android: "Allow the app to open in Obsidian"

### ISSUE THREAD

**Issue by adamhl8** [YukiGasai/obsidian-google-calendar#135] opened 2023-06-17 16:25 UTC
I have everything setup and working on desktop Obsidian but I'm not able to login on mobile for some reason. I have the correct JS origins and redirect URIs in my OAuth client. I get through the Google auth without issue and end up on `https://google-auth-obsidian-redirect.vercel.app/callback` which says `Allow the app to open in Obsidian`. Not too familiar with OAuth but I assume I'm supposed to get redirected back to the Obsidian app?

Any help is greatly appreciated. Thanks!

**Comment by YukiGasai** [comment] 2023-06-17 17:18
Does the browser show a popup similar to this one?
![Screenshot_20230617-191749.png](https://github.com/YukiGasai/obsidian-google-calendar/assets/38146192/2ec9ada1-0bc7-4016-8950-58a51640fe0e)

**Comment by YukiGasai** [comment] 2023-06-17 17:25
Thank you for bringing this issue up. I was able to reproduce this and will work on a fix ^^.

**Comment by adamhl8** [comment] 2023-06-17 17:26
Thanks! FWIW I also tried a few different browsers (Chrome, Brave, and Firefox).

**Comment by YukiGasai** [comment] 2023-06-18 18:42
Hi, 
I updated the [Redirect Server](https://github.com/YukiGasai/ObsidianGoogleCalendarAuth) and it should work again. Please test it yourself.

I am currently working on my bachelors thesis and have the auth with this plugin as a topic. Because of this, I made some changes, which broke the current version of the auth process.

If the login works for you, you can close this issue.

**Comment by adamhl8** [comment] 2023-06-18 22:36
It works, thank you for this amazing plugin :)

**Comment by utopicchaotica** [comment] 2023-06-21 16:54
This is still broken for me :(

**Comment by YukiGasai** [comment] 2023-06-21 17:24
You are right, please try again.

**Comment by utopicchaotica** [comment] 2023-06-29 15:27
Working now, thanks so much!

**Closed** 2023-06-29 19:46 UTC
Labels: bug

**Comment by mathisgauthey** [comment] 2023-07-06 21:45
Hey there, it doesn't work for me. I get the "Allow the app to open in Obsidian. The source code for this page is in visible on Github" message.

It works on desktop perfectly though, and I added the two URL for JavaScript and for the Redirect. Don't know what's wrong.
